# Generated by Django 5.0.3 on 2024-04-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=120)),
                ('value', models.IntegerField()),
                ('ubication', models.CharField(max_length=120)),
            ],
        ),
    ]
