# Generated by Django 5.0.3 on 2024-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_ventas_ventasapple'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=120)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
